export * from './validateUsername'
export * from './validateNames'
export * from './validateLastNames'
export * from './validateDPI'
export * from './validateAddress'
export * from './validatePhone'
export * from './validateEmail'
export * from './validateJob'
export * from './validateMonthlyIncome'
export * from './validateType'

